"""initial schema

Revision ID: c58c9125a057
Revises: 
Create Date: 2026-09-27 12:42:03.028173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c58c9125a057'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('class', sa.String(length=32), nullable=False),
    sa.Column('spec', sa.String(length=32), nullable=False),
    sa.Column('faction', sa.String(length=16), nullable=True),
    sa.Column('server', sa.String(length=64), nullable=True),
    sa.Column('talents', sa.JSON(), nullable=True),
    sa.Column('gear', sa.JSON(), nullable=True),
    sa.Column('simc_import_raw', sa.Text(), nullable=True),
    sa.Column('character_media', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_stats',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('haste', sa.Float(), nullable=True),
    sa.Column('crit', sa.Float(), nullable=True),
    sa.Column('hit', sa.Float(), nullable=True),
    sa.Column('mastery', sa.Float(), nullable=True),
    sa.Column('versatility', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('combat_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('combat_log_version', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sim_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('spec', sa.String(length=32), nullable=False),
    sa.Column('apl_definition', sa.JSON(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('sim_type', sa.String(length=16), nullable=False),
    sa.Column('external_report_id', sa.String(length=64), nullable=True),
    sa.Column('external_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('combat_log_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('encounter_type', sa.String(length=16), nullable=True),
    sa.Column('difficulty', sa.String(length=16), nullable=True),
    sa.Column('keystone_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['combat_log_id'], ['combat_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combat_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('ability_id', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('overhealing', sa.Integer(), nullable=True),
    sa.Column('is_crit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('combat_events', schema=None) as batch_op:
        batch_op.create_index('ix_combat_events_encounter_event_type', ['encounter_id', 'event_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combat_events', schema=None) as batch_op:
        batch_op.drop_index('ix_combat_events_encounter_event_type')

    op.drop_table('combat_events')
    op.drop_table('encounters')
    op.drop_table('sim_runs')
    op.drop_table('combat_logs')
    op.drop_table('character_stats')
    op.drop_table('characters')
    # ### end Alembic commands ###
